config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :attendance_requests, except: :edit
  get 'attendance_requests/:id/perform_attendance', to: 'attendance_requests#edit', as: 'perform_attendance'

  resources :reminders

  match "attendance_requests/filter_by_priority" => "attendance_requests#filter_by_priority", :via => :post
  
  devise_for :users, controllers: { registrations: 'registrations' }
  root 'welcome#index'
  get '/index', to: 'welcome#index', as: 'index'
  get '/about', to: 'welcome#about', as: 'about'
  get '/contact', to: 'welcome#contact', as: 'contact'
  get '/coordinator/:id', to: 'welcome#show'
  get '/coordinators', to: 'welcome#coordinators'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  authenticated :user do
    get 'admins/backoffice' => 'admins#backoffice'
    get 'coordinators/backoffice' => 'coordinators#coordinators_backoffice'
    # get 'students/backoffice' => 'students#students_backoffice'
  end

  authenticated :user do
    namespace :admins do
      resources :coordinators, except: :show
      resources :abouts, only: %i[index edit update]
    end
  end

  authenticated :user do
    resources :students
  end

  authenticated :user do
    namespace :coordinators do
      resources :infos
    end
  end

  # Credit forms routes
  resources :credit_forms
  # get 'credit_forms/new', to: 'credit_forms#new'
end

app/models/attendance_request.rb
class AttendanceRequest < ApplicationRecord
  belongs_to :user
  validates :user, presence: true
  validates :description, presence: true
  attr_accessor :position
  enum status: {aguardando: 'aguardando' , atendido: 'atendido'}
  enum priority_student: {normal: 'normal', 'em condição': 'em condição', outros: 'outros'}

  private
  after_initialize do
    unless self.created_at.nil?
      @position = AttendanceRequest.where("status = 'aguardando' AND created_at < '#{self.created_at}' ").count
      @position += 1;
    end
  end

end

app/controllers/attendance_requests_controller.rb
class AttendanceRequestsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_attendance_request, only: [:show, :edit, :update, :destroy]
  

  # GET /attendance_requests
  # GET /attendance_requests.json
  def index
    if current_user.has_role? :coordinator or current_user.has_role? :admin
      @attendance_requests = AttendanceRequest.joins(:user).where("users.course_id = #{current_user.course_id}").all
    else
      @attendance_requests = AttendanceRequest.where(user_id: current_user.id).all
    end
    render :index
  end

  # GET /attendance_requests/1
  # GET /attendance_requests/1.json
  def show
  end

  # GET /attendance_requests/new
  def new
    @attendance_request = AttendanceRequest.new
  end

  # GET /attendance_requests/1/edit
  def edit
  end

  # POST /attendance_requests
  # POST /attendance_requests.json
  def create
    @attendance_request = AttendanceRequest.new(user: current_user, description: get_description_param)

    respond_to do |format|
      if @attendance_request.save
        format.html { redirect_to attendance_requests_path, notice: 'Attendance request was successfully created.' }
        format.json { render :index, status: :created, location: @attendance_request }
      else
        format.html { render :new }
        format.json { render json: @attendance_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attendance_requests/1
  # PATCH/PUT /attendance_requests/1.json
  def update
    respond_to do |format|
      if @attendance_request.update(attendance_request_params)
        format.html { redirect_to attendance_requests_path, notice: 'Attendance request was successfully updated.' }
        format.json { render :index, status: :ok, location: @attendance_request }
      else
        format.html { render :edit }
        format.json { render json: @attendance_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendance_requests/1
  # DELETE /attendance_requests/1.json
  def destroy
    @attendance_request.destroy
    respond_to do |format|
      format.html { redirect_to attendance_requests_url, notice: 'Attendance request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  #filtra os atendimento pelo tipo de prioridade
  def filter_by_priority
    priority_student = filter_params[:priority_student]
    if !priority_student.include?("Todas")
      @attendance_requests = AttendanceRequest.where("Lower(priority_student) = ?", "#{priority_student.downcase}").all
    else
      @attendance_requests = AttendanceRequest.all.order(priority_student: :asc)
    end
    render json: { html: render_to_string(partial: 'attendances_requests_list')  }
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attendance_request
      @attendance_request = AttendanceRequest.find(params[:id])
    end

    def get_description_param
      attendance_request_params.to_h[:description]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attendance_request_params
      params.require(:attendance_request).permit(:description, :details)
    end

    def filter_params
      params.permit(:priority_student)
    end
end

app/helpers/attendance_requests_helper.rb
module AttendanceRequestsHelper
end

app/views/attendance_requests/_attendances_requests_list.html.erb
<% @attendance_requests.each do |attendance_request| %>
  <tr>
      <td><%= attendance_request.position %></td>
      <td><%= attendance_request.user.name %></td>
      <td><%= attendance_request.created_at.strftime("%d/%m/%Y %H:%M") %></td>
      <td><%= attendance_request.status.capitalize %></td>
      <td><%= attendance_request.description %></td>
      <td><%= attendance_request.priority_student.capitalize %></td>
      <td><%= link_to 'Realizar Atendimento', perform_attendance_path(attendance_request) %></td>
      <td><%= link_to (fa_icon "trash", class: 'text-danger lixeira'), attendance_request, method: :delete, data: { confirm: 'Are you sure?' }, :class => "lixeira" %></td>
  </tr>
<% end %>

app/views/attendance_requests/_form.html.erb
<% 
  isCoordinator = true if current_user.has_role? :coordinator || false
  user_form = isCoordinator ? attendance_request.user : current_user
%>

<%= form_with(model: attendance_request, local: true) do |form| %>
  <% if attendance_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(attendance_request.errors.count, "error") %> prohibited this attendance_request from being saved:</h2>

      <ul>
      <% attendance_request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label>Nome</label>
    <input type="text" class="form-control" value="<%= user_form.name %>" disabled readonly>
  </div>

  <div class="form-group">
    <label>Curso</label>
    <input type="text" class="form-control" value="<%= user_form.course.name %>" disabled readonly>
  </div>


  <div class="form-group">
    <label>Tipo de pedido</label>
    <%= form.text_field :description , {class: 'form-control', disabled: isCoordinator, readonly: isCoordinator }  %>
  </div>

  <% if  current_user.has_role? :coordinator %>
  <div class="form-group">
    <label>Detalhes</label>
    <%= form.text_area :details , {class: 'form-control'}%>
  </div>
  <% end %>

  <%= form.submit "Confirmar Requisição", class: 'btn btn-primary mb-2' %>
<% end %>

app/views/attendance_requests/_list.html.erb
    <div class='row'>
    <div class='col-12'>
        <h2>Requisição de atedimento </h2>
        <p id="notice"><%= notice %></p>
        <table class="table">
            <thead>
                <tr>
                <th>Posição</th>
                <th>Aluno</th>
                <th>Data Pedidos</th>
                <th>Status</th>
                <th>Descrição</th>
                <th>Ações</th>
                </tr>
            </thead>

            <tbody>
                <% @attendance_requests.each do |attendance_request| %>
                <tr>
                    <td><%= attendance_request.position %></td>
                    <td><%= attendance_request.user.name %></td>
                    <td><%= attendance_request.created_at.strftime("%d/%m/%Y %H:%M") %></td>
                    <td><%= attendance_request.status %></td>
                    <td><%= attendance_request.description %></td>
                    <td><%= link_to 'Remover Requisição', attendance_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                    <!--  <td><%# link_to 'Remover Requisição', attendance_request, method: :delete, data: { confirm: 'Are you sure?' } %></td> %> -->
                </tr>
                <% end %>
            </tbody>
        </table>

        <br>
        <% if  current_user.has_role? :student %>
        <%= link_to 'Requisitar Atendimento', new_attendance_request_path , class:'btn btn-primary' %>
        <% end %>
    </div>
</div>

app/views/attendance_requests/_list_coordinator.html.erb
    <div class='row'>
        <div class="offset-md-6 col-md-6 form-group row py-2">
            <label for="priority_filter" class="col-form-label">Filtrar por prioridade: </label>
            <div class="col-sm-8">
                <%= 
                select_tag(:priority_filter, 
                options_for_select([['Todas','Todas'], ['Em condição','Em condição'],['Normal','Normal'],['Outros', 'Outros']]), 
                {class: "form-control"})
                %>
            </div>
        </div>
    <div class='col-12'>
        <h2>Requisição de atedimento </h2>
        <p id="notice"><%= notice %></p>
        <table class="table">
            <thead>
                <tr>
                <th>Posição</th>
                <th>Aluno</th>
                <th>Data Pedidos</th>
                <th>Status</th>
                <th>Descrição</th>
                <th>Prioridade</th>
                <th colspan="2">Ações</th>
                </tr>
            </thead>

            <tbody class="attendances-requests-list">
                <%= render partial: 'attendances_requests_list', attendances: @attendance_requests %>
            </tbody>
        </table>
    </div>
</div>

app/views/attendance_requests/_list_student.html.erb
    <div class='row'>
    <div class='col-12'>
        <h2>Requisição de atedimento </h2>
        <table class="table">
            <thead>
                <tr>
                <th>Posição</th>
                <th>Aluno</th>
                <th>Data Pedidos</th>
                <th>Descrição</th>
                <th>Status</th>
                <th>Ações</th>
                </tr>
            </thead>

            <tbody>
                <% @attendance_requests.each do |attendance_request| %>
                <tr>
                    <td><%= attendance_request.position %></td>
                    <td><%= attendance_request.user.name %></td>
                    <td><%= attendance_request.created_at.strftime("%d/%m/%Y %H:%M") %></td>
                    <td><%= attendance_request.description %></td>
                    <td><%= attendance_request.status.capitalize %></td>
                    <td><%= link_to (fa_icon "trash", class: 'text-danger '), attendance_request, method: :delete, data: { confirm: 'Are you sure?' }, :class => "lixeira" %></td>
                </tr>
                <% end %>
            </tbody>
        </table>

        <br>
        <%= link_to 'Requisitar Atendimento', new_attendance_request_path , class:'btn btn-primary' %>
    </div>
</div>

app/views/attendance_requests/edit.html.erb
<div class='container attendace-request'>
	<div class='row'>
		<div class='col-12'>
            <h1>Realizando o atedimento de <%= @attendance_request.user.name %></h1>

            <%= render 'form', attendance_request: @attendance_request %>

            <%= link_to 'Back', attendance_requests_path, class:'btn btn-danger' %>
        </div>
    </div>
</div>

app/views/attendance_requests/filter_by_priority.js.erb
$('.attendances-requests-list').html("<%= j (render partial: 'attendances_requests_list') %>")

app/views/attendance_requests/index.html.erb
<p id="notice"><%= notice %></p>
<div class='container attendace-request'>
	<div class='row'>
		<div class='col-12'>
		<% if  current_user.has_role? :student %>
			<h2>Para entrar na fila de espera: </h2>

			<ul>
				<li>Preenchimento Formulário de Requisição de atedimento</li>
				<li>Verificar disponibilidade de antedimento do coordenador</li>
				<li>Verificar se o atendimento necessitado está listado nos tipo de requisições</li>
			</ul>

				</div>
			</div>
			<%= render 'attendance_requests/list_student', attendance_request: @attendance_request %>
		<% elsif  current_user.has_role? :coordinator %>
			<%= render 'attendance_requests/list_coordinator', attendance_request: @attendance_request %>
		<% end %>
</div>

app/views/attendance_requests/new.html.erb
<div class='container attendace-request'>
	<div class='row'>
		<div class='col-12'>
            <h1>Nova Requisição de atedimento</h1>

            <%= render 'form', attendance_request: @attendance_request %>

            <%= link_to 'Back', attendance_requests_path, class:'btn btn-danger' %>
        </div>
    </div>
</div>

app/views/attendance_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @attendance_request.user %>
</p>

<p>
  <strong>Status:</strong>
  <%= @attendance_request.status %>
</p>

<p>
  <strong>Attendance:</strong>
  <%= @attendance_request.attendance %>
</p>

<%= link_to 'Edit', edit_attendance_request_path(@attendance_request) %> |
<%= link_to 'Back', attendance_requests_path %>