config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :attendance_requests, except: :edit
  get 'attendance_requests/:id/perform_attendance', to: 'attendance_requests#edit', as: 'perform_attendance'

  resources :reminders

  match "attendance_requests/filter_by_priority" => "attendance_requests#filter_by_priority", :via => :post
  
  devise_for :users, controllers: { registrations: 'registrations' }
  root 'welcome#index'
  get '/index', to: 'welcome#index', as: 'index'
  get '/about', to: 'welcome#about', as: 'about'
  get '/contact', to: 'welcome#contact', as: 'contact'
  get '/coordinator/:id', to: 'welcome#show'
  get '/coordinators', to: 'welcome#coordinators'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  authenticated :user do
    get 'admins/backoffice' => 'admins#backoffice'
    get 'coordinators/backoffice' => 'coordinators#coordinators_backoffice'
    # get 'students/backoffice' => 'students#students_backoffice'
  end

  authenticated :user do
    namespace :admins do
      resources :coordinators, except: :show
      resources :abouts, only: %i[index edit update]
    end
  end

  authenticated :user do
    resources :students
  end

  authenticated :user do
    namespace :coordinators do
      resources :infos
    end
  end

  # Credit forms routes
  resources :credit_forms
  # get 'credit_forms/new', to: 'credit_forms#new'
end

app/controllers/admins/coordinators_controller.rb
# frozen_string_literal: true

# Controller for admins controll all coordinators
# Controller para que o admin do sistema tenha acesso aos usuários com a
# role de coordenador no sistema
class Admins::CoordinatorsController < AdminsController
  before_action :set_coordinator, only: %i[destroy edit update]
  before_action :get_all_courses, only: %i[create edit update new]
  # GET /coordinators
  # GET /coordinators.json
  # Método index dos coordenadores
  def index
    @coordinators = User.with_role(:coordinator)
  end

  # Método new dos coordenadores
  def new
    @coordinator = User.new
  end

  # Método create dos coordenadores
  # :reek:DuplicateMethodCall { allow_calls: ['format.html', 'format2.html'] }
  def create
    @coordinator = User.new(coordinator_params)
    @coordinator.add_role :coordinator
    respond_to do |format|
      if @coordinator.save
        format.html { redirect_to admins_coordinators_path, notice: 'Coordenador criado com sucesso' }
      else
        format.html { render :new }
      end
    end
  end

  # Método edit dos coordenadores
  def edit; end

  # Método Update dos coordenadores
  # :reek:DuplicateMethodCall
  def update
    respond_to do |format|
      if @coordinator.update_without_password(coordinator_params)
        format.html { redirect_to admins_coordinators_path, notice: 'Coordenador editado com sucesso' }
      else
        format.html { render :edit }
      end
    end
  end

  # Método destroy dos coordenadores
  # DELETE /coordinators/1
  # DELETE /coordinators/1.json
  def destroy
    @coordinator.destroy
    respond_to do |format|
      format.html { redirect_to admins_coordinators_url, notice: 'Coordenador excluído com sucesso' }
    end
  end

  private

  # Recebe coordenador por id
  # Use callbacks to share common setup or constraints between actions.
  def set_coordinator
    @coordinator = User.find(params[:id])
  end

  # Parâmetros do coordenador
  # Never trust parameters from the scary internet, only allow the white list through.
  def coordinator_params
    params.require(:user).permit(:name, :email, :password, :course_id)
  end

  # Método para pegar todos os cursos de um coordenador
  def get_all_courses
    @courses = Course.all
  end
end

app/controllers/coordinators/infos_controller.rb
# frozen_string_literal: true

# Controller para que o coordenador do sistema tenha acesso as suas informações
class Coordinators::InfosController < CoordinatorsController
  before_action :authenticate_user!
  before_action :set_coordinator, only: %i[edit update]
  # GET /coordinators
  # GET /coordinators.json
  # Mostra as informações do coordenador
  def index
    @coordinator = current_user
  end

  # Método update das infos do coordenador
  def update
    respond_to do |format|
      if @coordinator.update_without_password(coordinator_params)
        flash[:success] = 'Sucesso na edição dos dados do coordenador'
        format.html { redirect_to coordinators_infos_path, notice: 'Informações atualizadas com sucesso.' }
        format.json { render :show, status: :ok, location: @coordinator }
      else
        flash[:danger] = 'Erro na edição dos dados do coordenador'
        format.html { render :edit }
        format.json { render json: @coordinator.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Seta o coordenador a partir do usuario logado pelo devise
  # Use callbacks to share common setup or constraints between actions.
  def set_coordinator
    @coordinator = current_user
  end

  # Parâmetros do coordenador
  # Never trust parameters from the scary internet, only allow the white list through.
  def coordinator_params
    params.require(:user).permit(:name, :notices, :office_hours, :email, :password)
  end
end

app/controllers/coordinators_controller.rb
# frozen_string_literal: true

# Controller para que o coordenador do sistema tenha acesso ao seu backoffice
class CoordinatorsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_coordinator

  private

  # Apenas permite coordenadores logados
  def check_coordinator
    redirect_to root_path unless current_user.has_role? :coordinator
  end
  end

app/helpers/admins/coordinators_helper.rb
# frozen_string_literal: true

# Helper para coordenadores
module Admins::CoordinatorsHelper
end

app/views/admins/coordinators/_form.html.erb
<%= form_for @coordinator, url: aux do |f| %>
  <% if @coordinator.errors.any? %>
    <div class="alert alert-warning">
      <h5>Opa, temos alguns problemas:</h5>

      <ul class="mb-0">
        <% @coordinator.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :course %>
    <%= f.select( :course_id, @courses.collect { |course| [course.name, course.id] }, {}, { :class => 'form-control' }) %>
  </div>

  <div class="actions">
    <%= f.submit 'Enviar', class: "btn btn-success" %>
    <span>&nbsp;|&nbsp;</span>
    <%= link_to "Voltar", admins_coordinators_path, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admins/coordinators/edit.html.erb
<div class="container pb-4">
	<h2 class="mt-4">Editar coordenador</h2>
	<hr class="divider">

	<div class="card-body">
		<%= render partial: "form", locals: { aux: admins_coordinator_path } %>
  </div>

	<%# link_to 'Mostrar', @coordinator %>
	<%= link_to 'voltar', admins_coordinators_path %>
</div>

app/views/admins/coordinators/index.html.erb
<div class="container pb-4">
  <h2 class="mt-4">Coordenadores</h2>
  <hr class="divider">

  <div class="card">
    <div class="card-body">
      <table class="table">
        <thead>
          <tr>
            <th>Nome</th>
            <th>Email</th>
            <th>Course</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% unless @coordinators.nil? %>
            <% @coordinators.each do |coordinator| %>
              <tr>
                <td>
                  <%= coordinator.name %>
                </td>

                <td>
                  <%= coordinator.email %>
                </td>

                <td>
                  <%= coordinator.course.name %>
                </td>
                
                <td>
                  <%= link_to 'Editar', edit_admins_coordinator_path(coordinator), class: "btn btn-sm btn-primary" %>
                </td>
                <td>
                  <%= link_to 'Excluir', admins_coordinator_path(coordinator), method: :delete, data: { confirm: 'Você tem certeza?' }, class: "btn btn-sm btn-danger" %>
                </td>
              </tr>
              <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  
  <br>
  
  <%= link_to 'Novo Coordenador', new_admins_coordinator_path, class: "btn btn-success" %>

  <br>
  <br>
  <br>
  <%= link_to 'voltar', admins_backoffice_path, class: "btn btn-sm btn-primary" %>
</div>

app/views/admins/coordinators/new.html.erb
<div class="container pb-4">
  <h2 class="mt-4">Novo Usuário</h2>
  <hr class="divider">

  <div class="card">
    <div class="card-body">
      <%= render partial: "form", locals: { aux: admins_coordinators_path } %>
    </div>
  </div>
</div>