config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :attendance_requests, except: :edit
  get 'attendance_requests/:id/perform_attendance', to: 'attendance_requests#edit', as: 'perform_attendance'

  resources :reminders

  match "attendance_requests/filter_by_priority" => "attendance_requests#filter_by_priority", :via => :post
  
  devise_for :users, controllers: { registrations: 'registrations' }
  root 'welcome#index'
  get '/index', to: 'welcome#index', as: 'index'
  get '/about', to: 'welcome#about', as: 'about'
  get '/contact', to: 'welcome#contact', as: 'contact'
  get '/coordinator/:id', to: 'welcome#show'
  get '/coordinators', to: 'welcome#coordinators'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  authenticated :user do
    get 'admins/backoffice' => 'admins#backoffice'
    get 'coordinators/backoffice' => 'coordinators#coordinators_backoffice'
    # get 'students/backoffice' => 'students#students_backoffice'
  end

  authenticated :user do
    namespace :admins do
      resources :coordinators, except: :show
      resources :abouts, only: %i[index edit update]
    end
  end

  authenticated :user do
    resources :students
  end

  authenticated :user do
    namespace :coordinators do
      resources :infos
    end
  end

  # Credit forms routes
  resources :credit_forms
  # get 'credit_forms/new', to: 'credit_forms#new'
end

app/controllers/credit_forms_controller.rb
# frozen_string_literal: true

# Controller para que os alunos do sistema façam requisições pelos formulários de concessão de créditos
class CreditFormsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_credit_form, only: %i[show edit update destroy]

  # Método index dos forms de concessão
  def index
    if current_user.has_role?(:coordinator) || current_user.has_role?(:admin)
      @credit_forms = CreditForm.all
    elsif current_user.has_role? :student
      @credit_forms = CreditForm.where(user_id: current_user)
    end
  end

  # Método new dos forms de concessão
  def new
    @credit_form = current_user.credit_forms.build
    1.times { @credit_form.credit_items.build }
  end

  # Método show dos forms de concessão
  def show
    @items = @credit_form.credit_items
  end

  # Método create dos forms de concessão
  def create
    @credit_form = current_user.credit_forms.build(credit_form_params)
    if @credit_form.save
      flash[:success] = 'Seu formulário de aproveitamento de créditos foi criado com sucesso'
      redirect_to @credit_form
    else
      render :new
    end
  end

  # Método edit dos forms de concessão
  def edit; end

  # Método update dos forms de concessão
  def update
    if @credit_form.update(credit_form_params)
      flash[:success] = 'Formulário de aproveitamento de créditos editado com sucesso'
      redirect_to @credit_form
    else
      render :edit
    end
  end

  # Método destroy dos forms de concessão
  def destroy
    @credit_form.destroy
    redirect_to credit_forms_path
  end

  private

  # Pega o form de concessão pela id
  def set_credit_form
    @credit_form = CreditForm.find(params[:id])
  end

  # Parâmetros dos form de concessão
  def credit_form_params
    params.require(:credit_form).permit(:user_id, :name, :matricula, :email, :cellphone,
                                        :curso, :requisition_number, :sei, :received_at,
                                        credit_items_attributes: %i[id credit_form description group
                                                                    workload requested_credits_amount document _destroy])
  end
end

app/helpers/credit_forms_helper.rb
# frozen_string_literal: true

# :nocov:
# Helper do formulario de creditos de concessão
module CreditFormsHelper
  # Helper para remover fields 
  def link_to_remove_fields(name, f)
    f.hidden_field(:_destroy) + link_to_function(name, 'remove_fields(this)')
  end
  
  # Helper para adicionar fields
  def link_to_add_fields(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, child_index: "new_#{association}") do |builder|
      render(association.to_s.singularize + '_fields', f: builder)
    end
    link_to_function(name, "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")")
  end
end
# :nocov:

app/views/credit_forms/_credit_item_fields.html.erb
<div class="container fields">
  <div class="card">
    <div class="card-body">
      <div class="form-group">
        <%= f.label :description, "Descrição" %><br/>
        <%= f.text_area :description, :rows => 3, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :group, "Grupo" %><br/>
        <%= f.number_field :group, class: "form-control", min: 0 , max:100, step: 1 %>
      </div>
      <div class="form-group">
        <%= f.label :workload, "Carga horária" %><br/>
        <%= f.number_field :workload, class: "form-control", min: 0 , max:1000, step: 1 %>
      </div>
      <div class="form-group">
        <%= f.label :requested_credits_amount, "Quantidade de créditos solicitados" %><br/>
        <%= f.number_field :requested_credits_amount, class: "form-control", min:0, max: 100, step: 1 %>
      </div>
      <div class="form-group">
        <%= f.label :document, 'Documentação' %><br/>
        <%= f.file_field :document, class: "form-control" %>
      </div>

      <%= f.hidden_field :_destroy %>
      <p class="text-right"><%= link_to_remove_fields 'Remover Item', f %></p>
    </div>
  </div>
  <hr class="divider">  
</div>

app/views/credit_forms/_form.html.erb
<%= form_for @credit_form do |f| %>
  <% if @credit_form.errors.any? %>
    <div class="alert alert-warning">
      <h5>Opa, temos alguns problemas:</h5>

      <ul class="mb-0">
        <% @credit_form.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= link_to_add_fields "Adicionar Item", f, :credit_items %>
    <%= f.fields_for :credit_items do |builder| %>
      <%= render 'credit_item_fields', f: builder %>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit 'Enviar', class: "btn btn-success" %>
    <span>&nbsp;|&nbsp;</span>
    <%= link_to "Voltar", credit_forms_path, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/credit_forms/edit.html.erb
<div class="container pb-4">
  <h2 class="mt-4">Editar Formulário de Concessão de Crédito</h2>
  <hr class="divider">

  <div class="card">
    <div class="card-body">
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/credit_forms/index.html.erb
<div class="container pb-4">
  <h2 class="mt-4">Formulários de Concessão de Crédito</h2>
  <hr class="divider">

  <div class="card">
    <div class="card-body">
      <table class="table">
        <thead>
          <tr>
            <th>Aluno</th>
            <th>Email</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% unless @credit_forms.nil? %>
            <% @credit_forms.each do |credit_form| %>
              <tr>
                <td>
                  <%= User.find(credit_form.user_id).name %>
                </td>

                <td>
                  <%= User.find(credit_form.user_id).email %>
                </td>
                
                <td>
                  <%= link_to 'Ver Mais', credit_form, class: "btn btn-sm btn-success" %>
                </td>
                
                <td>
                  <%= link_to 'Editar', edit_credit_form_path(credit_form), class: "btn btn-sm btn-primary" %>
                </td>

                <td>
                  <%= link_to 'Excluir', credit_form_path(credit_form), method: :delete, data: { confirm: 'Você tem certeza?' }, class: "btn btn-sm btn-danger", id:"EXCLUIR" %>
                </td>
              </tr>
              <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  
  <br>
  
  <%= link_to 'Novo Formulário', new_credit_form_path, class: "btn btn-success", id: 'NOVOFORMULARIO' %>
</div>

app/views/credit_forms/new.html.erb
<div class="container pb-4">
  <h2 class="mt-4">Novo Formulário de Concessão de Crédito</h2>
  <hr class="divider">
  
  <div class="card">
    <div class="card-body">
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/credit_forms/show.html.erb
<h1 class="text-center">Formulário #<%= @credit_form.id %></h1>

<div class="card">
  <div class="card-body">
    <h2>
      <%= User.find(@credit_form.user_id).name %>
    </h2>
  </div>
</div>

<div class="row">
  <% @items.each_with_index do | item, i | %>
    <div class="col-sm-4">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">
            Item #<%= i %>
          </h5>
          <p class="card-text">
            <%= item.description %>
          </p>
          <ul>
            <li>Grupo: <%= item.group %></li>
            <li>Carga Horária: <%= item.workload %></li>
            <li>Qtd de Créditos solicitados: <%= item.requested_credits_amount %></li>  
          </ul>        
          <%= link_to "Download Anexo", rails_blob_path(item.document, disposition: "attachment"), class: 'btn btn-primary view-pdf' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="text-center">
  <%= link_to 'Editar', edit_credit_form_path(@credit_form), class: "btn btn-success" %> |
  <%= link_to 'Voltar', credit_forms_path, class: "btn btn-primary" %>
</div>